metrics:
  scope:
    prefix: "promremotebench"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

debugListenAddress: 0.0.0.0:9004
